---
- name: Disable root login via SSH
  hosts: all
  become: true

  tasks:
    - name: Edit SSH configuration file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        backrefs: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
